---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - openvpn_config_folder is defined
      - domain_name is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  docker_container:
    name: "{{ application_name }}-app"
    image: "kylemanna/openvpn:2.4"
    capabilities: ["NET_ADMIN"]
    restart_policy: "always"
    log_driver: "awslogs"
    cleanup: true
    memory: "10MB"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}-app"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}:/etc/openvpn"
    ports:
      - "1194:1194/udp"
    env:
      VIRTUAL_HOST: "{{ domain_name }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "1194"

- name: Copy vpn config
  copy:
    src: "{{ openvpn_config_folder }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}"
    owner: ubuntu
    group: ubuntu
    force: true
    mode: 0644
    directory_mode: 0775

# TODO: The container ip retrieval is missing
# TODO : Maybe IP forwarding needs to be forced to 1 every time.
# TODO : I had to manually connect the container to the bridge network with docker network connect bridge openvpn-app to get the ip.
# TODO: And then after inspecting I got the ip for the command below
#
# - name: Add container route for the ip pool
#   shell:
#   cmd: ip route add 192.168.255.0/24 via 172.17.0.2 dev docker0
#
# - name: Add container route for the static ips
#   shell:
#   cmd: ip route add 192.168.254.0/24 via 172.17.0.2 dev docker0
